### ISSUE TITLE
GPL-free licensing?

### ISSUE THREAD

**Issue by ItsCubeTime** [syeysk/tool_py2c_translator#1]
Hi, I would like to use this in a closed source project (which GPL does not allow). Is there any chance that the project could be made available under a different license as well (eg MIT)?

**Comment by syeysk** [comment]
Hi,
Is Apache 2.0 good for your project? It's like MIT. If it's good, I will change the license tomorrow

@ItsCubeTime

**Comment by syeysk** [comment]
So, if you need the decorator (https://github.com/harishtpj/PyCer/issues/2) I will do it.

Could you open the issue about it here? I will start the work.

**Comment by ItsCubeTime** [comment]
Apache 2.0 looks fine to me as well

> Could you open the issue about it here? I will start the work.

That's very generous of you :) Here you go https://github.com/syeysk/sy_py2c/issues/2
